import type { Metadata } from "next";
import React from 'react'
import './global.css';

export const metadata: Metadata = {
  title: "Bicycle Theft Checker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
